import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { LoginComponent } from './login/login.component';
import { HomeComponent } from './home/home.component';
import { RegistrationComponent } from './registration/registration.component';
import { WelcomepageComponent } from './welcomepage/welcomepage.component';
import { NavComponent } from './nav/nav.component';
import {SocialLoginModule, AuthServiceConfig, GoogleLoginProvider } from "angular-6-social-login";
import { ForgetpasswordComponent } from './forgetpassword/forgetpassword.component';
import { LoginotpComponent } from './loginotp/loginotp.component';
import { MainpageComponent } from './mainpage/mainpage.component';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';

export function getAuthServiceConfigs() {
  let config = new AuthServiceConfig(
      [
        {
          id: GoogleLoginProvider.PROVIDER_ID,
          provider: new GoogleLoginProvider("Your-Google-Client-Id")
        },
      ]
  );
  return config;
}

@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    HomeComponent,
    RegistrationComponent,
    WelcomepageComponent,
    NavComponent,
    ForgetpasswordComponent,
    LoginotpComponent,
    MainpageComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    ReactiveFormsModule,
    SocialLoginModule
  ],
  providers: [
    {
      provide: AuthServiceConfig,
      useFactory: getAuthServiceConfigs
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
  
 }
